controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


soap_service:
    path: /soap/service
    controller: App\Controller\SoapController::soapService