<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWO60yXp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWO60yXp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWO60yXp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWO60yXp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWO60yXp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WO60yXp',
    'container.build_id' => '7d248b0b',
    'container.build_time' => 1699820192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWO60yXp');
