# Generated by Django 4.2.7 on 2023-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_station", models.CharField(max_length=100)),
                ("arrival_station", models.CharField(max_length=100)),
                ("departure_date", models.DateTimeField()),
                ("arrival_date", models.DateTimeField()),
                ("seats_number", models.IntegerField()),
                ("first_class_seats", models.IntegerField()),
                ("business_class_seats", models.IntegerField()),
                ("standard_class_seats", models.IntegerField()),
            ],
        ),
    ]
