# Generated by Django 4.2.7 on 2023-11-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0002_station_alter_train_arrival_station_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="arrival_station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_station",
                to="idk.station",
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="departure_station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_station",
                to="idk.station",
            ),
        ),
    ]
