# Generated by Django 4.2.7 on 2023-11-10 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0003_alter_train_arrival_station_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="country",
        ),
        migrations.AddField(
            model_name="station",
            name="postal_code",
            field=models.CharField(
                max_length=5,
                null=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="arrival_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="departure_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="arrival_date",
            field=models.DateField(default="2023-11-10"),
        ),
        migrations.AlterField(
            model_name="train",
            name="departure_date",
            field=models.DateField(default="2023-11-10"),
        ),
    ]
