# Generated by Django 4.2.7 on 2023-11-10 14:08

from django.db import migrations

def empty_database(apps, schema_editor):
    """Empty the Station and Train tables."""
    Station = apps.get_model("idk", "Station")
    Train = apps.get_model("idk", "Train")
    Station.objects.all().delete()
    Train.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0004_remove_station_country_station_postal_code_and_more"),
    ]

    operations = []
