# Generated by Django 4.2.7 on 2023-11-10 14:08

from django.db import migrations
from pathlib import Path
import csv

def populate_station_data(apps, schema_editor):
    """Populate the Station table with some data."""
    file_path = Path(__file__).resolve().parent / '..' / 'data' / 'station_data.csv'
    Station = apps.get_model("idk", "Station")
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            Station.objects.create(name=row[0], postal_code=row[1], city=row[2])


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0005_empty_database"),
    ]

    operations = [
        migrations.RunPython(populate_station_data)
        ]
