# Generated by Django 4.2.7 on 2023-11-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0007_remove_train_seats_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("business", "Business"),
                            ("standard", "Standard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                ("fixed_price", models.FloatField(default=0.0)),
                ("flexible_price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name="train",
            name="business_class_seats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_class_seats",
                to="idk.seatgroup",
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="first_class_seats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_class_seats",
                to="idk.seatgroup",
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="standard_class_seats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_class_seats",
                to="idk.seatgroup",
            ),
        ),
    ]
