# Generated by Django 4.2.7 on 2024-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idk", "0009_populate_trains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="arrival_date",
            field=models.DateField(default="2024-01-07"),
        ),
        migrations.AlterField(
            model_name="train",
            name="departure_date",
            field=models.DateField(default="2024-01-07"),
        ),
    ]
