# Generated by Django 5.0.1 on 2024-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idk', '0010_alter_train_arrival_date_alter_train_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_date',
            field=models.DateField(default='2024-01-08'),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_date',
            field=models.DateField(default='2024-01-08'),
        ),
    ]
